CREATE DATABASE yeticave
	DEFAULT CHARSET utf8
    DEFAULT COLLATE utf8_general_ci;

USE yeticave;

CREATE TABLE categories (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(128) NOT NULL UNIQUE,
    code VARCHAR(64) NOT NULL UNIQUE
);

CREATE TABLE lots (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    dt_add TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    name VARCHAR(128) NOT NULL,
    description TEXT NOT NULL,
    img VARCHAR(128) NOT NULL,
    price MEDIUMINT UNSIGNED NOT NULL,
    dt_end DATE NOT NULL,
    step INT UNSIGNED NOT NULL,
    cat_id INT NOT NULL,
    author_id INT NOT NULL,
    win_id INT NULL
);

CREATE TABLE bets (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    dt_add TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    price INT UNSIGNED NOT NULL,
    user_id INT NOT NULL,
    lot_id INT NOT NULL
);

CREATE TABLE users (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    dt_add TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    email VARCHAR(128) NOT NULL UNIQUE,
    password VARCHAR(128) NOT NULL,
    name VARCHAR(128) NOT NULL,
    contact TEXT NOT NULL,
    role_id INT NOT NULL
);
# BINDING TABLES
CREATE TABLE users_to_lots (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    lot_id INT NOT NULL
);
CREATE TABLE users_to_bets (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    bet_id INT NOT NULL
);

CREATE TABLE roles (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    type VARCHAR(64) NOT NULL
);
    
